export const SECURITY_PAGE_COPY = {
  eyebrow: 'Protect your account',
  title: 'Security',
  description: 'Manage sign-in protection, recovery options, and active devices.',
  forcedSetupNotice: 'Please set up an authenticator app to continue.',
  verifiedNotice: 'Verification complete. You can now make changes.',
  states: {
    on: 'On',
    off: 'Off',
    active: 'Active',
    enabled: 'Enabled',
    verified: 'Verified',
    pending: 'Pending',
    unavailable: 'Unavailable',
    recommended: 'Recommended',
  },
  summary: {
    email: 'Email',
    password: 'Password',
    mfa: 'Two-factor authentication',
    device: 'Current device',
  },
  mfa: {
    title: 'Two-factor authentication',
    disabledDescription: 'Protect sign-ins, withdrawals, and account changes with a code from your authenticator app.',
    enabledDescription: 'Your account is protected with an authenticator app.',
    setupRecommended: 'Recommended',
    setupInProgress: 'Setup in progress',
    setupEnabled: 'On',
    introTitle: 'Enable two-factor authentication',
    introDescription: 'Use an authenticator app to generate a 6-digit code when signing in, withdrawing funds, or changing security settings.',
    appGuidance: 'You can use Google Authenticator, 1Password, Authy, Microsoft Authenticator, or another compatible app.',
    scanTitle: 'Scan this QR code',
    scanDescription: 'Open your authenticator app and scan the QR code below.',
    setupKeyFallback: "Can't scan it?",
    showSetupKeyAction: 'Show setup key',
    hideSetupKeyAction: 'Hide setup key',
    copySetupKeyAction: 'Copy setup key',
    confirmTitle: 'Enter the 6-digit code',
    confirmDescription: 'Type the current code from your authenticator app to finish setup.',
    codeLabel: 'Authenticator code',
    codeIncompleteError: 'Code must be 6 digits.',
    codeInvalidError: 'That code did not work. Check your authenticator app and try again.',
    recoveryTitle: 'Save your recovery codes',
    recoveryDescription: 'Use these codes to access your account if you lose your authenticator app. Each code can only be used once.',
    recoveryConfirmTitle: 'Have you saved your recovery codes?',
    recoveryConfirmDescription: 'You may not be able to see them again.',
    startAction: 'Start setup',
    enableAction: 'Enable 2FA',
    manageAction: 'Manage 2FA',
    recoverySaved: 'Recovery codes saved',
    savedCodesAction: "I've saved my codes",
    savedCodesConfirmAction: 'Yes, I saved them',
    goBackAction: 'Go back',
    cancelAction: 'Cancel setup',
    backToSecurityAction: 'Back to security',
    disableTitle: 'Turn off 2FA',
    disableDescription: 'You need your current authenticator code or a recovery code to turn off two-factor authentication.',
    refreshRecoveryAction: 'Generate new recovery codes',
  },
  recovery: {
    title: 'Recovery codes',
    description: 'Use these codes to sign in if you lose access to your authenticator app. Save them in a secure, offline place.',
    empty: 'No recovery codes are visible right now. Generate a new set when you need to replace the current codes.',
    setupPending: 'Recovery codes appear here after you finish setup.',
    copyAllAction: 'Copy all',
  },
  sessions: {
    title: 'Active devices',
    overviewDescription: 'You are signed in on this device.',
    description: 'Review where your account is signed in.',
    manageAction: 'Manage devices',
    currentDeviceLabel: 'Current device',
    otherDevicesLabel: 'Other devices',
    emptyOtherDevices: 'No other active devices found.',
    revokeOthersAction: 'Sign out all other devices',
    revokeOthersConfirmTitle: 'Sign out other devices?',
    revokeOthersConfirmDescription: 'This will remove access from all devices except this one.',
    revokeCurrentConfirmTitle: 'Sign out of this device?',
    revokeCurrentConfirmDescription: 'You will need to sign in again to continue using 4real.',
    currentAction: 'Sign out of this device',
    otherAction: 'Sign out',
  },
  accountActions: {
    title: 'Account actions',
    description: 'Use this when you are done on the current device.',
  },
} as const;

export interface SecuritySetupFlowInput {
  setupRequested: boolean;
  mfaEnabled: boolean;
}

export function shouldOpenTotpSetupFlow(input: SecuritySetupFlowInput) {
  return input.setupRequested
    && !input.mfaEnabled;
}
